GEANT/CAT

web/resources/inc/header.php

fix lang header

---

.github/issue_template.md

starting template for eduroamCAT issues - need to add further guidance related to
debugging for each platform (e.g. what we request for Windows when there are issues)

template for issues

---

web/admin/js/silverbullet.js
web/lib/admin/http/DeleteUserCommand.php
web/lib/admin/view/YesNoDialogBox.php

Couple fixes for invitations QR code

Couple fixes.

---

translation/bg_BG/diagnostics.po
translation/ca_ES/diagnostics.po
translation/cs_CZ/diagnostics.po
translation/de_DE/diagnostics.po
translation/diagnostics.pot
translation/el_GR/diagnostics.po
translation/es_ES/diagnostics.po
translation/fi_FI/diagnostics.po
translation/fr_FR/diagnostics.po
translation/gl_ES/diagnostics.po
translation/hr_HR/diagnostics.po
translation/hu_HU/diagnostics.po
translation/it_IT/diagnostics.po
translation/nb_NO/diagnostics.po
translation/nl_NL/diagnostics.po
translation/pl_PL/diagnostics.po
translation/pt_PT/diagnostics.po
translation/sk_SK/diagnostics.po
translation/sl_SI/diagnostics.po
translation/sr_RS/diagnostics.po
translation/sv_SE/diagnostics.po
web/skins/modern/diag/diag.php

Self evident in the title :)
The .mo files aren't regenerated in this patch.

Fix spelling of Diagnistic

---

devices/linux/Files/Makefile

The question is how do we solve the dependencies with the used tools? Should we add a ``requierements.txt``?
But this file is only for developer, so it shouldnt be a problem.
You should inlcude this Makefile in your test suite.

Add Makefile

---

devices/ms/Files/common.inc
devices/ms/Files/geant_link.inc
devices/ms/WindowsCommon.php

Reverts GEANT/CAT#140
This should have gone into the Release 2.0 branch

Revert "Add windows arm support for GEANTLink"

---

devices/linux/Files/main.py

The installer use the ``XDG_CONFIG_HOME`` directory. It it is not defined it use the default path ``$HOME/.config``. See #150.

Use xdg_config_home

---

.scrutinizer.yml
devices/linux/Files/eduroam_linux_institution.sh

Hello @twoln,
here is my first draft. A lot of code should be known for you. I will do soon more, but you could already give me feedback so I could improve problems.

Add linux bash installer

---

devices/linux/DeviceLinuxSh.php
devices/linux/Files/eduroam_linux_institution.sh
devices/linux/Files/eduroam_linux_main.sh

Remove the error with double questionsmarks, e.g. "Weiter??"

Fix ask func

---

devices/linux/DeviceLinuxSh.php
devices/linux/Files/eduroam_linux_institution.sh
devices/linux/Files/eduroam_linux_main.sh

Linux bash installer

---

devices/linux/Files/main.py

New in version 3.5 ([Source](https://docs.python.org/3/library/typing.html)).

Add typing

---

devices/linux/Files/main.py

I think we should drop python2-support (https://pythonclock.org/).

Drop python2 support

---

devices/linux/Files/main.py

Hello @twoln ,
I think we should further test iwd, but since some people already use it, we could offer the configurations in the python code yet. 
I could do more. But we have to discuss at first how we decide when we use `wpa_supllicant` or `iwd`?

Add IWD support

---

devices/linux/Files/main.py

Through the new github actions we could detect problems with a certain python version. This PR fix these problems.

Fix Github Actions error

---

devices/linux/DeviceLinux.php

It is better python style and after this I could hopefully remove the global variables.

Use __main__ attribute

---

devices/linux/Files/main.py

I couldn't test this changes, but I hope it will solve #177. But So please test it before you merge.

Managed idp without NetworkManager

---

tutorials/UserAPI.md

Just some simple changes to the UserAPI tutorial (tutorials/UserAPI.md)
- Add listLanguages to the bullet-pointed list.
- Correct some typos.
- Add spaces to JSON properties.

UserAPI tutorial changes

---

devices/ms/MsLanProfile.php

This fixes https://github.com/GEANT/CAT/issues/247

Fix wired profiles on windows

---

.github/workflows/linux_tests.yml

This will fix this CI warning:

Update GitHub Actions

---

.github/workflows/linux_tests.yml

* 2260a3965de372a01c5def86fcb8b3da6f123682
* fc623ffb14a2e6897b1a55200a65205fb8c5a114
This will avoid these warnings and errors:

Backport updates of GitHub Actions
