- web/admin/API.php
- web/admin/inc/option_parse.inc.php
Quoting from the [wiki](https://wiki.geant.org/display/H2eduroam/A+guide+to+eduroam+CAT+for+federation+administrators):
> The POST parameter option[Sx] specifies the name of the attribute to set; yes, that is a literal character "S" followed by an integer number of your choice (numbers do not need to be consecutive nor start at 1). All options can occur more than once.
>|Option Name|Explanation|
|---|---|
|profile-api:eaptype | integer value of a supported EAP type, as per the following table. Preference of EAP types is determined by the order induced by their option[Sx] sequence number.|
My understanding of the above is that if x < y, then option[Sx] < option[Sy] -- or perhaps the same in descending order.
However that is not the case. PHP produces a hierarchy of associative arrays from …
> Admin API: fix sequence number ordering for option parameters

- devices/linux/Files/requirements.txt
- devices/linux/Files/requirements_dev.txt
Only with ``requirements_dev.txt`` works the ``Makefile``. The ``requirements.txt`` is for people who want only use it. But its only for information and not for the normal eduroam user.
I added also the module ``keyring``. I will program soon that it will work with the keyring.
> Add requirements

- devices/ms/Files/common.inc
- devices/ms/Files/geant_link.inc
- devices/ms/WindowsCommon.php
Hello guys,
I had the idea that we could add arm support. So here are a pull request with few changes.
It works only with ``nsis3.04`` but is still compatible with  older ``nsis`` versions. I use the ``IsNative`` function from the new ``nsis 3.04`` version (see [Release Notes](https://nsis.sourceforge.io/Docs/AppendixF.html#v3.04)).
You have to update also the submodule from GEANTLink so that you could use latest ``GEANTLINK-ARM64.exe``.
> Add windows arm support for GEANTLink

- devices/ms/Files/geant_link.inc
Hello,
I read at the mailing list that we need only GEANTLink until windows 10 build 1803. So we don't have to install GEANTLink starting from 1803, do we?
I used for this the nsis 3.04 and the ``AtMostWaaS`` macro from ``WinVer.nsh``.
Additional question: which branch should I use? Still ``release_2_0``?
> Use geantlink only if needed

- devices/ms/Files/common.inc
Changes:
* put Compress settings on the top
* add CRCCheck
* add ManifestDPIaware
* remove XPStyle
The ``ManifestDPIaware`` is important that the installer text is not blurry anymore. But you have to use at least nsis3.0.
> Add ManifestDPIaware and CRCCheck settings

- devices/linux/Files/main.py
Pyqt5 creates an empty dbus package, which will crash the software without further details. See #211 for more
> Testing for empty dbus package caused by PyQT5

- core/AbstractProfile.php
- core/common/X509.php
Fix #221
Skip `AbstractProfile::CA_CLASH_ADDED` when the new CA has the same name with an existing CA, but also an identical public key.
> Suppress AbstractProfile::CA_CLASH_ADDED for a new CA with the same public key

- devices/linux/Files/main.py
Changed a regex that splits the fields of `subject=` to ignore commas inside double quotes. Added a comment, because the syntax of the forward lookup makes it hard to understand.
This is meant to fix the following error:
```
File "/home/marek/Downloads/eduroam-linux-PdM-polimi-TLS.py", line 547, in __process_p12
cert_prop[cert_field[0].lower()] = cert_field[1]
IndexError: list index out of range
```
It is caused by the comma after street name, creating a field `32"`. The same certificate works fine with windows installer so I assume that the address is OK and parsing should be improved
```
O = Politecnico di Milano, street = "Piazza Leonardo da Vinci, 32", ST = Milano, 
```
> Fix linux installer for some street addresses

- web/user/about_cat.inc.php
Opening the "About eduroam CAT" page raises an error message.
Pretty obviously it's because a parameter was forgotten in sprintf() in about_cat.inc.php#36.
https://github.com/GEANT/CAT/blob/b53bc299c7e822c7abd8deb1ee1a9e44f3f465da/web/user/about_cat.inc.php#L36
It seems like this got introduced in https://github.com/GEANT/CAT/commit/60177439c7803c3560405a4e5667fb8f21526fbd.
This PR would fix it.
> add missing argument

- devices/linux/Files/main.py
A deviation from the default values in the `DEBUG_ON` variable could only occur after executing `run_installer()` for the first time. Therefore with `--debug` specified the variable still evaluated to `False` causing a missing debug message when failing to import the `dbus` module.
> Fix: missing initial debug messages

- devices/ms/DeviceW8W10.php
This obviously produces an error at the moment.
`\core\common\Entity::getAttributeValue` returns a value. It won't be an array.
Error message:
`PHP Warning:  Trying to access array offset on value of type null in devices/ms/DeviceW8W10.php on line 306`
> Fix: access array offset on value

- .github/workflows/linux_tests.yml
Apply least possible privileges to workfkows to limit the damage compromised actions can do to the repository. By specifying any permission explicitly all others are set to none.
* [Keeping your GitHub Actions and workflows secure](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
> Limit permissions of GitHub workflows

- .github/workflows/linux_tests.yml
See [Supported runners and hardware resources](https://docs.github.com/fr/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). This will fix this issue:
Note that Ubuntu 18.04 is also being deprecated, fortunately the deprecation schedule has been extended until April 2023:
[GitHub Actions: The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)
Finally, Ubuntu 22.04 will be added by a different merge request: #253.
> Remove Ubuntu 16.04 from CI tests

- .github/workflows/linux_tests.yml
Move linting to `ubuntu-22.04`, with its default Python version 3.10. Unless you prefer `ubuntu-latest`?
Add new versions of Python on Ubuntu 22.04. Should I add them for Ubuntu 18.04 and 20.04 too?
> Test Linux installer on newer platforms

- .github/workflows/linux_tests.yml
The Ubuntu 18.04 Actions runner is deprecated, and not available any more starting April 2023:
[GitHub Actions: The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/):
> * update: we extended the deprecation schedule until April 2023 with updated dates for brownouts.
Also update lintign to Python 3.11.
> Stop testing on Ubuntu 18.04

- core/DeviceConfig.php
should be pretty easy to understand the bug
> Fixes a wrong use of \config\ConfAssistant::CONSORTIUM['CONSORTIUM']['interworking-domainname-fallback']

- devices/linux/Files/main.py
After finding that this script did not run on my linux installation, I found that there is no mention that it requires dbus-python to be installed. Added a line in message in the error that CAT produces to help in future.
> Add context as to why NM cannot be located

- core/UserNetAPI.php
The User API currently sends JSON payload with an text/html header. This leads to JSON being displayed as if it was HTML, with strange results.
The correct Content-Type according to RFC 4627 is application/json. When sending the appropriate Content-Type, there is no need to further escape the JSON payload.
Finally, add a newline after the JSON data, so it doesn't screw up the terminal when you use curl.
> Change how JSON is delivered in the user API

- ansible/ManagedSP/templates/daemon/fr_restart.py
- devices/linux/Files/main.py
No need to set it explictly.
https://docs.python.org/3/howto/unicode.html#unicode-literals-in-python-source-code
> Encoding is implicitly UTF-8 in Python 3

- devices/linux/Files/main.py
The tkinter library is very common and supports all the same features that yad does.
> Implemented tkinter graphics on Linux

- devices/linux/Files/main.py
The code for tkinter graphics was missing a return statement as well as the file picker. "load_pkcs12" was removed from pyOpenSSL on version 23.3.0, so a check for its availability has been added.
> Fix tkinter and check for load_pkcs12 on Linux

- devices/linux/Files/main.py
This reverts commit eb66053041fe42d95719ecb97ddb8f3c0d8549ed.
Do not apply rule UP006 when targeting Python < 3.9.
> Revert "Apply ruff/pyupgrade rule UP006"

- .github/workflows/linux_tests.yml
- Bump Ubuntu 22.04 to 24.04.
- Bump Ubuntu 20.04 to 22.04 because the 20.04 runner image has been retired:
[Ubuntu 20 image is closing down](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/#ubuntu-20-image-is-closing-down)
Fixes #322.
Unfortunately, this means Python 3.6 cannot be tested any more, from the CI error on Ubuntu 22.04 runners:
```
Version 3.6 was not found in the local cache
Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
> Update Ubuntu runners
